# Generated by Django 4.0.4 on 2022-05-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradingsystem', '0002_alter_semester_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
