# Generated by Django 4.0.4 on 2022-05-31 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradingsystem', '0003_alter_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='classID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradingsystem.class'),
        ),
    ]
